### -------------------- VARIABLES --------------------
@baseLocal = http://localhost:3000
@baseRender = https://pick-and-play-mic3.onrender.com

@adminEmail = admin_teddy@test.com
@adminPassword = adminTeddy123!
@memberEmail = member@test.com
@memberPassword = Password123!

@movieIdLocal = 69cffbe525a04936e35030ce
@gameIdLocal = 69d0010f25a04936e35030dd
@groupIdLocal = 69d41dfd45cb8f2b34a982ea
@groupDeleteIdLocal = 69d4008721773c4724a11293
@gameUpdateIdLocal = 69d0010f25a04936e35030de
@movieDeleteIdLocal = 69d421fe45cb8f2b34a982ec
@gameDeleteIdLocal = 69d0010f25a04936e35030de
@selfUserIdLocal = 69d0010f25a04936e35030de
@memberIdLocal = 69d0010f25a04936e35030df

@movieIdRender = 69cffbe525a04936e35030d1
@gameIdRender = 69d0010f25a04936e35030da
@groupIdRender = 69cef917e06ab30dbfe77bd5
@groupDeleteIdRender = 69d41dfd45cb8f2b34a982ea
@gameUpdateIdRender = 69d0010f25a04936e35030de
@movieUpdateIdRender = 69d42586885fa045a9d13b9e
@gameDeleteIdRender = 69d425bd885fa045a9d13b9f
@selfUserIdRender = 69d0010f25a04936e35030de
@memberIdRender = 69d0010f25a04936e35030df

### AUTH ENDPOINTS ###

### Register New User
POST {{baseLocal}}/auth/register
Content-Type: application/json
{
    "username": "newuser",
    "email": "newuser@test.com",
    "password": "Password123!"
}

### Login (redirects to dashboard on success)
# POST http://localhost:3000/auth/login
POST {{baseLocal}}/auth/login
Content-Type: application/json
{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

### Logout
POST {{baseLocal}}/auth/logout
Content-Type: application/json

### Get Current User
GET {{baseLocal}}/auth/me
### RESOURCE ENDPOINTS ###

GET {{baseLocal}}/movies

GET {{baseLocal}}/games

###
GET {{baseLocal}}/api/groups

###
GET {{baseLocal}}/movies/{{movieIdLocal}}

###
GET {{baseLocal}}/games/{{gameIdLocal}}

## Previous route kept for comparison
# ###
# GET http://localhost:3000/groups/69d3d54d57e0bf4ab8a099c0

###
GET {{baseLocal}}/api/groups/{{groupIdLocal}}

POST {{baseLocal}}/games HTTP/1.1
content-type: application/json

{
    "title": "Cover Your Assets",
    "genre": "Table-top card game",
    "playtime": "1h30m",
    "minPlayers": "3",
    "maxPlayers": "6",
    "description": "Quite competitive. It's one against everyone.",
    "imageURL": "3862dbje1"
}

## Previous route/body kept for comparison
# ###
# POST http://localhost:3000/groups HTTP/1.1
# content-type: application/json
#
# {
#     "groupName": "Batman Team",
#     "votes": 4,
#     "winVote": 0,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
POST {{baseLocal}}/api/groups HTTP/1.1
content-type: application/json

{
    "groupName": "Batman Team",
    "activities": []
}

###
POST {{baseLocal}}/movies HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": "PG-13",
    "runtime": "1h45m",
    "description": "Shakespeare's Twelfth Night given a modern twist.",
    "imageURL": "eruhnj23" 
}

###
PUT {{baseLocal}}/movies/{{movieIdLocal}}

{
    "title": "Hotel Transylvania [2012]",
    "genre": "3D Animation, Quirky Comedy, Family, Monster Horror",
    "rating": 7,
    "runtime": "1h 31m",
    "description": "Dracula, who operates a high-end resort away from the human world, goes into overprotective mode when a boy discovers the resort and falls for the count's teenaged daughter. It's awesome!",
    "imageURL": "hotel.jpg" 
}

###
PUT {{baseLocal}}/games/{{gameUpdateIdLocal}}

{
    "title": "Jenga",
    "genre": "Table top",
    "playtime": "1h 30m",
    "minPlayers": "2",
    "maxPlayers": "6",
    "description": "pretty fun game of building a tower and prevent it from tumbling down. Can be quite competitive. It's one against everyone.",
    "imageURL": "jenga.jpg" 
}

// Previous route kept for comparison (PUT not supported)
# ###
# PUT http://localhost:3000/groups/69d41dfd45cb8f2b34a982ea
#
# {
#     "groupName": "Batman Team",
#     "votes": 5,
#     "winVote": 0,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
PATCH {{baseLocal}}/api/groups/{{groupIdLocal}}
content-type: application/json

{
    "groupName": "Batman Team - Updated"
}

### Leave group (self-remove)
DELETE {{baseLocal}}/api/groups/{{groupIdLocal}}/members/{{selfUserIdLocal}}

### Admin remove member from group
DELETE {{baseLocal}}/api/groups/{{groupIdLocal}}/members/{{memberIdLocal}}

###
DELETE {{baseLocal}}/movies/{{movieDeleteIdLocal}}

## Previous route kept for comparison
# ###
# DELETE http://localhost:3000/groups/69d4008721773c4724a11293

###
DELETE {{baseLocal}}/api/groups/{{groupDeleteIdLocal}}

###
DELETE {{baseLocal}}/games/{{gameDeleteIdLocal}}

### -------------- RENDER LINKS REST API ---------------------------

POST {{baseRender}}/auth/login
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

###
GET {{baseRender}}/movies

## Previous route kept for comparison
# ###
# GET https://pick-and-play-mic3.onrender.com/groups 

###
GET {{baseRender}}/api/groups


###
GET {{baseRender}}/games 


###
GET {{baseRender}}/movies/{{movieIdRender}}


// Previous route kept for comparison
# ###
# GET https://pick-and-play-mic3.onrender.com/groups/69cef917e06ab30dbfe77bd5

###
GET {{baseRender}}/api/groups/{{groupIdRender}}

###
GET {{baseRender}}/games/{{gameIdRender}}


###
POST {{baseRender}}/movies HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": "PG-13",
    "runtime": "1h45m",
    "description": "Shakespeare's Twelfth Night given a modern twist.",
    "imageURL": "eruhnj23" 
}

###
POST {{baseRender}}/games HTTP/1.1
content-type: application/json

{
    "title": "Cover Your Assets",
    "genre": "Table-top card game",
    "playtime": "1h30m",
    "minPlayers": "3",
    "maxPlayers": "6",
    "description": "Quite competitive. It's one against everyone.",
    "imageURL": "3862dbje1"
}

###
POST {{baseRender}}/api/groups HTTP/1.1
content-type: application/json

{
    "groupName": "Wonder Woman Team",
    "activities": []
}

###
PUT {{baseRender}}/movies/{{movieUpdateIdRender}} HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": 8.5,
    "runtime": "1h 45m",
    "description": "Shakespeare's Twelfth Night given a modern twist. It's awesome! Righty-o",
    "imageURL": "eruhnj23" 
}

###
PUT {{baseRender}}/games/{{gameUpdateIdRender}} HTTP/1.1
content-type: application/json

{
    "title": "Jenga",
    "genre": "Board Game, Physical Skill, Tower Building",
    "playtime": "1h45",
    "minPlayers": 2,
    "maxPlayers": 4,
    "description": "A physical skill game where players take turns removing blocks from a tower and placing them on top. It's awesome! Update made",
    "imageURL": "ttjns43287"
}

// Previous route/body kept for comparison (PUT not supported)
# ###
# PUT https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea HTTP/1.1
# content-type: application/json
#
# {
#     "groupName": "",
#     "votes": ,
#     "winVote": ,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
PATCH {{baseRender}}/api/groups/{{groupDeleteIdRender}} HTTP/1.1
content-type: application/json

{
    "groupName": "Wonder Woman Team - Updated"
}

### Render leave group (self-remove)
DELETE {{baseRender}}/api/groups/{{groupDeleteIdRender}}/members/{{selfUserIdRender}}

### Render admin remove member from group
DELETE {{baseRender}}/api/groups/{{groupDeleteIdRender}}/members/{{memberIdRender}}

###
DELETE {{baseRender}}/movies/{{movieUpdateIdRender}}

###
DELETE {{baseRender}}/api/groups/{{groupDeleteIdRender}}

###
DELETE {{baseRender}}/games/{{gameDeleteIdRender}}
