### AUTH ENDPOINTS ###

### Create Test User
GET http://localhost:3000/auth/create-test-user

### Register New User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@test.com",
    "password": "Password123!"
}

### Login (redirects to dashboard on success)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin_teddy@test.com",
    "password": "adminTeddy123!"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

### Get Current User
GET http://localhost:3000/auth/me

### RESOURCE ENDPOINTS ###

### 
GET http://localhost:3000/movies

###
GET http://localhost:3000/games

## Previous route kept for comparison
# ###
# GET http://localhost:3000/groups/

###
GET http://localhost:3000/api/groups

###
GET http://localhost:3000/movies/69cffbe525a04936e35030ce

# ###
# GET http://localhost:3000/users

###
GET http://localhost:3000/games/69d0010f25a04936e35030dd

## Previous route kept for comparison
# ###
# GET http://localhost:3000/groups/69d3d54d57e0bf4ab8a099c0

###
GET http://localhost:3000/api/groups/69d3d54d57e0bf4ab8a099c0

###
# POST http://localhost:3000/localhost:3000/users HTTP/1.1
# content-type: application/json

# {

# }

POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
    "title": "Cover Your Assets",
    "genre": "Table-top card game",
    "playtime": "1h30m",
    "minPlayers": "3",
    "maxPlayers": "6",
    "description": "Quite competitive. It's one against everyone.",
    "imageURL": "3862dbje1"
}

## Previous route/body kept for comparison
# ###
# POST http://localhost:3000/groups HTTP/1.1
# content-type: application/json
#
# {
#     "groupName": "Batman Team",
#     "votes": 4,
#     "winVote": 0,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
POST http://localhost:3000/api/groups HTTP/1.1
content-type: application/json

{
    "groupName": "Batman Team",
    "activities": []
}

###
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": "PG-13",
    "runtime": "1h45m",
    "description": "Shakespeare's Twelfth Night given a modern twist.",
    "imageURL": "eruhnj23" 
}

//need to check
###
PUT http://localhost:3000/movies/69cffbe525a04936e35030ce

{
    "title": "Hotel Transylvania [2012]",
    "genre": "3D Animation, Quirky Comedy, Family, Monster Horror",
    "rating": 7,
    "runtime": "1h 31m",
    "description": "Dracula, who operates a high-end resort away from the human world, goes into overprotective mode when a boy discovers the resort and falls for the count's teenaged daughter. It's awesome!",
    "imageURL": "hotel.jpg" 
}

# PUT http://localhost:3000/localhost:3000/users/

# {

# }

//Need to check
###
PUT http://localhost:3000/games/69d0010f25a04936e35030de

{
    "title": "Jenga",
    "genre": "Table top",
    "playtime": "1h 30m",
    "minPlayers": "2",
    "maxPlayers": "6",
    "description": "pretty fun game of building a tower and prevent it from tumbling down. Can be quite competitive. It's one against everyone.",
    "imageURL": "jenga.jpg" 
}

// Previous route kept for comparison (PUT not supported)
# ###
# PUT http://localhost:3000/groups/69d41dfd45cb8f2b34a982ea
#
# {
#     "groupName": "Batman Team",
#     "votes": 5,
#     "winVote": 0,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
PATCH http://localhost:3000/api/groups/69d41dfd45cb8f2b34a982ea
content-type: application/json

{
    "groupName": "Batman Team - Updated"
}

### Leave group (self-remove)
DELETE http://localhost:3000/api/groups/69d41dfd45cb8f2b34a982ea/members/69d0010f25a04936e35030de

### Admin remove member from group
DELETE http://localhost:3000/api/groups/69d41dfd45cb8f2b34a982ea/members/69d0010f25a04936e35030df

//Add Id
###
DELETE http://localhost:3000/movies/69d421fe45cb8f2b34a982ec

//This needs checking
# ###
# DELETE http://localhost:3000/localhost:3000/users/

## Previous route kept for comparison
# ###
# DELETE http://localhost:3000/groups/69d4008721773c4724a11293

###
DELETE http://localhost:3000/api/groups/69d4008721773c4724a11293

//Add Id
###
DELETE http://localhost:3000/games/



### -------------- RENDER LINKS REST API ---------------------------

POST https://pick-and-play-mic3.onrender.com/auth/login
Content-Type: application/json

{
    "email": "admin_teddy@test.com",
    "password": "adminTeddy123!"
}

###
GET https://pick-and-play-mic3.onrender.com/movies


###
GET https://pick-and-play-mic3.onrender.com/3000/auth/create-test-user


## Previous route kept for comparison
# ###
# GET https://pick-and-play-mic3.onrender.com/groups 

###
GET https://pick-and-play-mic3.onrender.com/api/groups


###
GET https://pick-and-play-mic3.onrender.com/games 


###
GET https://pick-and-play-mic3.onrender.com/movies/69cffbe525a04936e35030d1

###
GET https://pick-and-play-mic3.onrender.com/3000/users/


// Previous route kept for comparison
# ###
# GET https://pick-and-play-mic3.onrender.com/groups/69cef917e06ab30dbfe77bd5

###
GET https://pick-and-play-mic3.onrender.com/api/groups/69cef917e06ab30dbfe77bd5

###
GET https://pick-and-play-mic3.onrender.com/games/69d0010f25a04936e35030da


###
POST https://pick-and-play-mic3.onrender.com/movies HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": "PG-13",
    "runtime": "1h45m",
    "description": "Shakespeare's Twelfth Night given a modern twist.",
    "imageURL": "eruhnj23" 
}

# ###
# POST https://pick-and-play-mic3.onrender.com/3000/users HTTP/1.1
# content-type: application/json

# {

# }

###
POST https://pick-and-play-mic3.onrender.com/games HTTP/1.1
content-type: application/json

{
    "title": "Cover Your Assets",
    "genre": "Table-top card game",
    "playtime": "1h30m",
    "minPlayers": "3",
    "maxPlayers": "6",
    "description": "Quite competitive. It's one against everyone.",
    "imageURL": "3862dbje1"
}

###
POST https://pick-and-play-mic3.onrender.com/api/groups HTTP/1.1
content-type: application/json

{
    "groupName": "Wonder Woman Team",
    "winVote": 8,
    "winVote": 0,
    "createdBy": null,
    "groupAdminId": null,
    "members": [],
    "activities": []
}

###
PUT https://pick-and-play-mic3.onrender.com/movies/69d42586885fa045a9d13b9e HTTP/1.1
content-type: application/json

{
    "title": "She's The Man",
    "genre": "Romantic Comedy",
    "rating": 8.5,
    "runtime": "1h 45m",
    "description": "Shakespeare's Twelfth Night given a modern twist. It's awesome! Righty-o",
    "imageURL": "eruhnj23" 
}


# ###
# PUT https://pick-and-play-mic3.onrender.com/users/ HTTP/1.1
# content-type: application/json

# {

# }

###
PUT https://pick-and-play-mic3.onrender.com/games/69d0010f25a04936e35030de HTTP/1.1
content-type: application/json

{
    "title": "Jenga",
    "genre": "Board Game, Physical Skill, Tower Building",
    "playtime": "1h45",
    "minPlayers": 2,
    "maxPlayers": 4,
    "description": "A physical skill game where players take turns removing blocks from a tower and placing them on top. It's awesome! Update made",
    "imageURL": "ttjns43287"
}

// Previous route/body kept for comparison (PUT not supported)
# ###
# PUT https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea HTTP/1.1
# content-type: application/json
#
# {
#     "groupName": "",
#     "votes": ,
#     "winVote": ,
#     "createdBy": null,
#     "groupAdminId": null,
#     "members": [],
#     "activities": []
# }

###
PATCH https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea HTTP/1.1
content-type: application/json

{
    "groupName": "Wonder Woman Team - Updated"
}

### Render leave group (self-remove)
DELETE https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea/members/69d0010f25a04936e35030de

### Render admin remove member from group
DELETE https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea/members/69d0010f25a04936e35030df



###
DELETE https://pick-and-play-mic3.onrender.com/movies/69d42586885fa045a9d13b9e


# ###
# DELETE https://pick-and-play-mic3.onrender.com/users/

###
DELETE https://pick-and-play-mic3.onrender.com/api/groups/69d41dfd45cb8f2b34a982ea

###
DELETE https://pick-and-play-mic3.onrender.com/games/69d425bd885fa045a9d13b9f
